[package]
name = "upl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
cookie_store = "0.22.1"
directories = "6.0.0"
reqwest = { version = "0.13.4", features = ["blocking", "multipart"] }
reqwest_cookie_store = { version = "0.10.0", features = ["serde"] }
serde = "1.0.229"
serde_json = "1.0.151"
